repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: no-commit-to-branch
      - id: end-of-file-fixer
        exclude_types:
          - json

      - id: trailing-whitespace
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: 62acdd0e6aaf398eb04af4a6fcd97a9f3f538668  # v0.1.22
    hooks:
      - id: shellcheck
